game = Game.create(turn: "white")

Rook.create(side: "white", row: 1, column: 1, captured: false, game_id: game.id)
Knight.create(side: "white", row: 1, column: 2, captured: false, game_id: game.id)
Bishop.create(side: "white", row: 1, column: 3, captured: false, game_id: game.id)
Queen.create( side: "white", row: 1, column: 4, captured: false, game_id: game.id)
King.create(side: "white", row: 1, column: 5, captured: false, game_id: game.id)
Bishop.create(side: "white", row: 1, column: 6, captured: false, game_id: game.id)
Knight.create(side: "white", row: 1, column: 7, captured: false, game_id: game.id)
Rook.create(side: "white", row: 1, column: 8, captured: false, game_id: game.id)
Pawn.create(side: "white", row: 2, column: 1, captured: false, game_id: game.id)
Pawn.create(side: "white", row: 2, column: 2, captured: false, game_id: game.id)
Pawn.create(side: "white", row: 2, column: 3, captured: false, game_id: game.id)
Pawn.create(side: "white", row: 2, column: 4, captured: false, game_id: game.id)
Pawn.create(side: "white", row: 2, column: 5, captured: false, game_id: game.id)
Pawn.create(side: "white", row: 2, column: 6, captured: false, game_id: game.id)
Pawn.create(side: "white", row: 2, column: 7, captured: false, game_id: game.id)
Pawn.create(side: "white", row: 2, column: 8, captured: false, game_id: game.id)
Pawn.create(side: "black", row: 7, column: 1, captured: false, game_id: game.id)
Pawn.create(side: "black", row: 7, column: 2, captured: false, game_id: game.id)
Pawn.create(side: "black", row: 7, column: 3, captured: false, game_id: game.id)
Pawn.create(side: "black", row: 7, column: 4, captured: false, game_id: game.id)
Pawn.create(side: "black", row: 7, column: 5, captured: false, game_id: game.id)
Pawn.create(side: "black", row: 7, column: 6, captured: false, game_id: game.id)
Pawn.create(side: "black", row: 7, column: 7, captured: false, game_id: game.id)
Pawn.create(side: "black", row: 7, column: 8, captured: false, game_id: game.id)
Rook.create(side: "black", row: 8, column: 1, captured: false, game_id: game.id)
Knight.create(side: "black", row: 8, column: 2, captured: false, game_id: game.id)
Bishop.create(side: "black", row: 8, column: 3, captured: false, game_id: game.id)
Queen.create( side: "black", row: 8, column: 4, captured: false, game_id: game.id)
King.create(side: "black", row: 8, column: 5, captured: false, game_id: game.id)
Bishop.create(side: "black", row: 8, column: 6, captured: false, game_id: game.id)
Knight.create(side: "black", row: 8, column: 7, captured: false, game_id: game.id)
Rook.create(side: "black", row: 8, column: 8, captured: false, game_id: game.id)
